{
 "title": "Asterisk Overview",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(asterisk_calls_processed{},job)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(asterisk_calls_processed{job=~\"$group\"},hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(asterisk_active_channels{hostname=~\"$host\"},instance)"
    }
   },
   {
    "name": "cpshost",
    "label": "CPS Hostname",
    "query": {
     "query": "label_values(asterisk_calls_processed{job=~\"$group\"},hostname)"
    }
   },
   {
    "name": "count",
    "label": "count",
    "query": {
     "query": "query_result(count(asterisk_sip_peers{hostname=~\"$host\",instance=~\"$instance\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Asterisk overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "calls processed since reboot $host",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_calls_processed{hostname=~\"$host\",instance=~\"$instance\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Asterisk version",
   "type": "table",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "asterisk_version_info{hostname=~\"$host\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "asterisk_system_uptime_seconds{hostname=~\"$host\",instance=~\"$instance\"} "
    },
    {
     "expr": "asterisk_last_reload_seconds{hostname=~\"$host\",instance=~\"$instance\"} "
    }
   ]
  },
  {
   "title": "Total $count SIP status table $host",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "asterisk_sip_peers{hostname=~\"$host\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SIP status graphical $host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time(asterisk_sip_peers{hostname=~\"$host\",instance=~\"$instance\"}[1m])",
     "legendFormat": "[SIP name : {{sipname}}] [Status : {{status}}] [Sip IP : {{host}}]"
    }
   ]
  },
  {
   "title": "Active channels $host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "last_over_time(asterisk_active_channels{hostname=~\"$host\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "asterisk active calls $host",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "last_over_time(asterisk_active_calls{hostname=~\"$host\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "exact operator channels",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "last_over_time(asterisk_active_channels{hostname=~\"$host\",instance=~\"$instance\"}[1m]) - last_over_time(asterisk_active_calls{hostname=~\"$host\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}